// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BatterySwapStationManagement.Repositories.PhongNT.Models;

public partial class BatteryPhongNT
{
    public Guid BatteryPhongNTId { get; set; }

    public string SerialNo { get; set; }

    public string Model { get; set; }

    public decimal Capacity { get; set; }

    public decimal SoHcurrent { get; set; }

    public Guid StationId { get; set; }

    public bool Status { get; set; }

    public virtual ICollection<BatteryHealthRecordPhongNT> BatteryHealthRecords { get; set; } = new List<BatteryHealthRecordPhongNT>();

    public virtual Station Station { get; set; }

    public virtual ICollection<SwapTransaction> SwapTransactionNewBatteries { get; set; } = new List<SwapTransaction>();

    public virtual ICollection<SwapTransaction> SwapTransactionOldBatteries { get; set; } = new List<SwapTransaction>();
}