// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BatterySwapStationManagement.Repositories.PhongNT.Models;

public partial class BatteryHealthRecordPhongNT
{
    public Guid RecordPhongNTId { get; set; }

    public Guid BatteryPhongNTId { get; set; }

    public decimal SoH { get; set; }

    public DateTime MeasuredAt { get; set; }

    public string Note { get; set; }

    public virtual BatteryPhongNT Battery { get; set; }
}