// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace BatterySwapStationManagement.Repositories.PhongNT.Models;

public partial class FA25_PRN232_SE1707_G5_BatterySwapStationManagement : DbContext
{
    public FA25_PRN232_SE1707_G5_BatterySwapStationManagement()
    {
    }

    public FA25_PRN232_SE1707_G5_BatterySwapStationManagement(DbContextOptions<FA25_PRN232_SE1707_G5_BatterySwapStationManagement> options)
        : base(options)
    {
    }

    public virtual DbSet<BatteryPhongNT> BatteriesPhongNT { get; set; }

    public virtual DbSet<BatteryHealthRecordPhongNT> BatteryHealthRecordsPhongNT { get; set; }

    public virtual DbSet<Driver> Drivers { get; set; }

    public virtual DbSet<StationBay> StationBays { get; set; }

    public virtual DbSet<Station> Stations { get; set; }

    public virtual DbSet<StationType> StationTypes { get; set; }

    public virtual DbSet<SwapTransaction> SwapTransactions { get; set; }

    public virtual DbSet<SystemUserAccount> SystemUserAccounts { get; set; }

    public virtual DbSet<Vehicle> Vehicles { get; set; }

//    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
//        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-9HSQ90N\\PHAT;Initial Catalog=FA25_PRN232_SE1707_G5_BatterySwapStationManagement;Integrated Security=True;Encrypt=True;TrustServerCertificate=True");

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
      => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BatteryPhongNT>(entity =>
        {
            entity.HasKey(e => e.BatteryPhongNTId).HasName("PK__Battery__5710805E68E1BDAC");

            entity.ToTable("BatteryPhongNT");

            entity.HasIndex(e => e.SerialNo, "UQ__Battery__5E5A535EBFF05415").IsUnique();

            entity.Property(e => e.BatteryPhongNTId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Capacity).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Model)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.SerialNo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.SoHcurrent)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("SoHCurrent");
            entity.Property(e => e.StationId)
                .HasColumnName("StationId");
            entity.Property(e => e.Status)
                .HasDefaultValue(true);
            entity.HasOne(d => d.Station)
                .WithMany(p => p.Batteries)
                .HasForeignKey(d => d.StationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Battery_Station");
        });


        modelBuilder.Entity<BatteryHealthRecordPhongNT>(entity =>
        {
            entity.HasKey(e => e.RecordPhongNTId).HasName("PK__BatteryH__FBDF78E9A0F39FD0");

            entity.ToTable("BatteryHealthRecord");

            entity.Property(e => e.RecordPhongNTId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.MeasuredAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Note).HasMaxLength(500);
            entity.Property(e => e.SoH).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.Battery).WithMany(p => p.BatteryHealthRecords)
                .HasForeignKey(d => d.BatteryPhongNTId)
                .HasConstraintName("FK_HealthRecord_Battery");
        });

        modelBuilder.Entity<Driver>(entity =>
        {
            entity.HasKey(e => e.DriverId).HasName("PK__Driver__F1B1CD04A6FD8B54");

            entity.ToTable("Driver");

            entity.HasIndex(e => e.Email, "UQ__Driver__A9D10534C7ED7703").IsUnique();

            entity.Property(e => e.DriverId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<StationBay>(entity =>
        {
            entity.HasKey(e => e.StationBayId).HasName("PK__StationB__F2DA60CD96AECE3D");

            entity.ToTable("StationBay");

            entity.Property(e => e.StationBayId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.StationId).HasColumnName("StationId");

            entity.HasOne(d => d.Station).WithMany(p => p.StationBays)
                .HasForeignKey(d => d.StationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StationBay_Station");
        });

        modelBuilder.Entity<Station>(entity =>
        {
            entity.HasKey(e => e.StationId).HasName("PK__StationP__AFF142127ACC0C7F");

            entity.ToTable("Station");

            entity.Property(e => e.StationId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("StationId");
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Latitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.Longitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.OpeningHour).HasMaxLength(100);
            entity.Property(e => e.StationTypeId).HasColumnName("StationTypeId");
            entity.Property(e => e.Status).HasDefaultValue(true);

            entity.HasOne(d => d.StationType).WithMany(p => p.Stations)
                .HasForeignKey(d => d.StationTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Station_StationType");
        });

        modelBuilder.Entity<StationType>(entity =>
        {
            entity.HasKey(e => e.StationTypeId).HasName("PK__StationT__2CDC7DFB7FAAD66C");

            entity.ToTable("StationType");

            entity.HasIndex(e => e.Code, "UQ__StationT__A25C5AA771E550BE").IsUnique();

            entity.Property(e => e.StationTypeId).HasColumnName("StationTypeId");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Note).HasMaxLength(500);
        });

        modelBuilder.Entity<SwapTransaction>(entity =>
        {
            entity.HasKey(e => e.TransactionId).HasName("PK__SwapTran__55433A6B3B9078D8");

            entity.ToTable("SwapTransaction");

            entity.Property(e => e.TransactionId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.StartAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.StationId).HasColumnName("Station");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Pending");
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Driver).WithMany(p => p.SwapTransactions)
                .HasForeignKey(d => d.DriverId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Swap_Driver");

            entity.HasOne(d => d.NewBattery).WithMany(p => p.SwapTransactionNewBatteries)
                .HasForeignKey(d => d.NewBatteryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Swap_NewBattery");

            entity.HasOne(d => d.OldBattery).WithMany(p => p.SwapTransactionOldBatteries)
                .HasForeignKey(d => d.OldBatteryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Swap_OldBattery");

            entity.HasOne(d => d.Station).WithMany(p => p.SwapTransactions)
                .HasForeignKey(d => d.StationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Swap_Station");
        });

        modelBuilder.Entity<SystemUserAccount>(entity =>
        {
            entity.HasKey(e => e.UserAccountId);

            entity.ToTable("System.UserAccount");

            entity.Property(e => e.UserAccountId).HasColumnName("UserAccountID");
            entity.Property(e => e.ApplicationCode).HasMaxLength(50);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.EmployeeCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RequestCode).HasMaxLength(50);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Vehicle>(entity =>
        {
            entity.HasKey(e => e.VehicleId).HasName("PK__Vehicle__476B54925E5494C1");

            entity.ToTable("Vehicle");

            entity.HasIndex(e => e.Vin, "UQ__Vehicle__C5DF234C58397BF3").IsUnique();

            entity.Property(e => e.VehicleId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.BatteryType)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Make)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Model)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Vin)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("VIN");

            entity.HasOne(d => d.Driver).WithMany(p => p.Vehicles)
                .HasForeignKey(d => d.DriverId)
                .HasConstraintName("FK_Vehicle_Driver");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}