// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BatterySwapStationManagement.Repositories.PhongNT.Models;

public partial class Station
{
    public Guid StationId { get; set; }

    public int StationTypeId { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public bool Status { get; set; }

    public int CapacitySlots { get; set; }

    public string OpeningHour { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public virtual ICollection<BatteryPhongNT> Batteries { get; set; } = new List<BatteryPhongNT>();

    public virtual ICollection<StationBay> StationBays { get; set; } = new List<StationBay>();

    public virtual StationType StationType { get; set; }

    public virtual ICollection<SwapTransaction> SwapTransactions { get; set; } = new List<SwapTransaction>();
}