// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BatterySwapStationManagement.Repositories.PhongNT.Models;

public partial class StationBay
{
    public Guid StationBayId { get; set; }

    public Guid StationId { get; set; }

    public string Code { get; set; }

    public bool IsActive { get; set; }

    public virtual Station Station { get; set; }
}