// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BatterySwapStationManagement.Repositories.PhongNT.Models;

public partial class SwapTransaction
{
    public Guid TransactionId { get; set; }

    public Guid DriverId { get; set; }

    public Guid StationId { get; set; }

    public Guid OldBatteryId { get; set; }

    public Guid NewBatteryId { get; set; }

    public DateTime StartAt { get; set; }

    public DateTime? EndAt { get; set; }

    public string Status { get; set; }

    public decimal TotalAmount { get; set; }

    public virtual Driver Driver { get; set; }

    public virtual BatteryPhongNT NewBattery { get; set; }

    public virtual BatteryPhongNT OldBattery { get; set; }

    public virtual Station Station { get; set; }
}