// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BatterySwapStationManagement.Repositories.PhongNT.Models;

public partial class Vehicle
{
    public Guid VehicleId { get; set; }

    public Guid DriverId { get; set; }

    public string Vin { get; set; }

    public string Make { get; set; }

    public string Model { get; set; }

    public string BatteryType { get; set; }

    public virtual Driver Driver { get; set; }
}