// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BatterySwapStationManagement.SOAPService.PhongNT;

[DataContract]

public partial class BatteryPhongNT
{
    [DataMember]
    public Guid BatteryPhongNTId { get; set; }
    [DataMember]
    public string SerialNo { get; set; }
    [DataMember]
    public string Model { get; set; }
    [DataMember]
    public decimal Capacity { get; set; }
    [DataMember]
    public decimal SoHcurrent { get; set; }
    [DataMember]
    public Guid StationId { get; set; }
    [DataMember]
    public bool Status { get; set; }
    [DataMember]
    public virtual ICollection<BatteryHealthRecordPhongNT> BatteryHealthRecords { get; set; } = new List<BatteryHealthRecordPhongNT>();
    [DataMember]
    public virtual Station Station { get; set; }
    [DataMember]
    public virtual ICollection<SwapTransaction> SwapTransactionNewBatteries { get; set; } = new List<SwapTransaction>();
    [DataMember]
    public virtual ICollection<SwapTransaction> SwapTransactionOldBatteries { get; set; } = new List<SwapTransaction>();
}