// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BatterySwapStationManagement.SOAPService.PhongNT;
[DataContract]
public partial class BatteryHealthRecordPhongNT
{
    [DataMember]
    public Guid RecordPhongNTId { get; set; }
    [DataMember]
    public Guid BatteryPhongNTId { get; set; }
    [DataMember]
    public decimal SoH { get; set; }
    [DataMember]
    public DateTime MeasuredAt { get; set; }
    [DataMember]
    public string Note { get; set; }
    [DataMember]
    public virtual BatteryPhongNT Battery { get; set; }
}