// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BatterySwapStationManagement.SOAPService.PhongNT;

public partial class Driver
{
    public Guid DriverId { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public bool Verified { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<SwapTransaction> SwapTransactions { get; set; } = new List<SwapTransaction>();

    public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();
}