// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BatterySwapStationManagement.SOAPService.PhongNT;

public partial class StationType
{
    public int StationTypeId { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public bool IsActive { get; set; }

    public string Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Station> Stations { get; set; } = new List<Station>();
}